compat: Fix building with newer versions of MSVC
Previously, MSVC's preprocessor happily parsed the #if line that
references __has_include_next, and ignored it (and as the start of
the line, `defined(__clang__)`, evaluates to zero, it doesn't make any
difference anyway).

Since MSVC around version 19.52.36629 (19.52 is currently in preview,
not a stable release), MSVC now errors out on this expression:

    ../include/compat/msvc\stdatomic.h(35): error C7780: function-like macro '__has_include_next' is not defined
    ../include/compat/msvc\stdatomic.h(35): fatal error C1017: invalid integer constant expression

Add a fallback definition of __has_include_next, to let the MSVC
preprocessor handle this cleanly.

In practice, this header isn't ever used with Clang though - if
stdatomic.h exists, then we don't add include/compat/msvc at all,
and we only add this directory if actually compiling with MSVC.