riscv64/ipred16: Fix build error with -Dbitdepths=16
When configuring and building dav1d with just the 16bp code paths using
 meson setup .. -Dbitdepths=16 there is an undefined reference to
 dav1d_dc_gen_8bpc_rvv due to a typo in src/riscv/64/ipred16.S.